/* eslint-disable eol-last */
const user = [
  {
    id: 1,
    firstName: 'ruhimbaza',
    lastName: 'Bertin',
    email: 'ruhimbazab@gmail.com',
    password: '$2a$10$lifw9U..bfUh0bsk7OopBedeLy6OtlvyvgfnMzPYBwVv8Hv3vh2zW',
    address: 'kigali',
    bio: 'scientist',
    occupation: 'software development',
    expertise: 'sostware architecture',
    userType: 'user',
  },
  {
    id: 2,
    firstName: 'ahishakiye',
    lastName: 'aline',
    email: 'aline@gmail.com',
    password: '$2a$10$lifw9U..bfUh0bsk7OopBedeLy6OtlvyvgfnMzPYBwVv8Hv3vh2zW',
    address: 'Nairobi',
    bio: 'researcher',
    occupation: 'advocacy',
    expertise: 'teaching',
    userType: 'mentor',
  },
  {
    id: 3,
    firstName: 'ngarambe',
    lastName: 'antoine',
    email: 'kagorora1@gmail.com',
    password: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJrYWdvcm9yYUBnbWFpbC5jb20iLCJ1c2VyVHlwZSI6ImFkbWluIiwiaWF0IjoxNTY2MjA1NjEzfQ._ZQfSMbDwvaOg_pSCfsqlZhVM4M7tihdH0M8dLIoqww',
    address: 'legos',
    bio: 'something',
    occupation: 'maintenance',
    expertise: 'maintainning systems',
    userType: 'admin',
  },
  {
    id: 4,
    firstName: 'manzi',
    lastName: 'James',
    email: 'manziJamesb@gmail.com',
    password: '$2a$10$lifw9U..bfUh0bsk7OopBedeLy6OtlvyvgfnMzPYBwVv8Hv3vh2zW',
    address: 'kigali',
    bio: 'scientist',
    occupation: 'software development',
    expertise: 'sostware architecture',
    userType: 'mentor',
  },
  {
    id: 5,
    firstName: 'manzi',
    lastName: 'James',
    email: 'kagorora@gmail.com',
    password: '$2a$10$lifw9U..bfUh0bsk7OopBedeLy6OtlvyvgfnMzPYBwVv8Hv3vh2zW',
    address: 'kigali',
    bio: 'scientist',
    occupation: 'software development',
    expertise: 'sostware architecture',
    userType: 'admin',
  },
];
// eslint-disable-next-line no-trailing-spaces
    
export default user;